FROM maven:3.8.2-openjdk-16-slim AS MAVEN_BUILD

COPY app/src ./src
COPY app/pom.xml ./pom.xml

RUN mvn clean package

FROM openjdk:11-jre-slim-bullseye

# copy only the artifacts we need from the first stage and discard the rest
COPY --from=MAVEN_BUILD /backend/target/backend-0.0.1-SNAPSHOT.jar /backend.jar

# set the startup command to execute the jar
CMD ["java", "-jar", "/backend.jar"]