version: '3.8'
services:
  sql-db:
    image: postgres:latest
    ports:
      - "127.0.0.1:5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres-db

  cache:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"