version: '3.8'
services:
  postgres:
    image: postgres:13.4
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres-db
    volumes:
      - ./mounts/postgres/data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:2.0.11
    hostname: mqtt
    ports:
      - "8883:8883"
    volumes:
      - ./configs/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  telegraf:
    image: telegraf:1.17.3
    hostname: telegraf
    environment:
      - INFLUX_URL=https://${SERVER_FQDN}/influxdb
    volumes:
      - ./configs/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./certs/telegraf:/etc/telegraf/secrets
      - ./mounts/telegraf:/tmp

  hub:
    image: hub-service:0.0.1-SNAPSHOT
    hostname: hub
    environment:
      - KAFKA_SERVERS_FQDN=${SERVER_FQDN}
    volumes:
      - ./certs/kafka-client:/etc/secrets/kafka-client
    depends_on:
      - postgres
      - mqtt
      - telegraf