[[tls.certificates]]
    certFile = "/secrets/traefik.crt"
    keyFile = "/secrets/traefik.key"

[tls.options]
    [tls.options.default]
        [tls.options.default.clientAuth]
            caFiles = ["/secrets/ca.crt"]
            clientAuthType = "RequireAndVerifyClientCert"

[tls.stores]
    [tls.stores.default]
        [tls.stores.default.defaultCertificate]
            certFile = "/secrets/traefik.crt"
            keyFile  = "/secrets/traefik.key"
