version: '3.8'
services:
  reverse-proxy:
    image: traefik:v2.4
    hostname: traefik
    command: 
      - --api.insecure=true 
      - --api.dashboard=false
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false

      - --log.level=DEBUG

      - --serversTransport.rootCAs=/secrets/ca.crt

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443

      - --providers.file.filename=/configs/traefik-dynamic.toml
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik:/configs
      - ./certs/traefik:/secrets
    labels: 
      - "traefik.enable=true"
    
  influxdb:
    hostname: influxdb
    image: influxdb:latest
    volumes:
      - ./mounts/influxdbv2:/.influxdbv2
    environment: 
      - INFLUXD_QUERY_CONCURRENCY=30
      - INFLUXD_QUERY_QUEUE_SIZE=50
    labels: 
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.docker.localhost`)"
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.enable=true"

      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"

  influxdb_cli:
    image: influxdb:latest
    links:
      - influxdb
    entrypoint: influx setup --bucket mybucket -t mytoken -o myorg --username=admin --password=admin123 --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb

  zoo1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zoo1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SECURE_CLIENT_PORT: 3181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2

      ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
      ZOOKEEPER_SERVER_CNXN_FACTORY: "org.apache.zookeeper.server.NettyServerCnxnFactory"
      ZOOKEEPER_AUTH_PROVIDER_X509: "org.apache.zookeeper.server.auth.X509AuthenticationProvider"
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/zoo/secrets/zoo1.keystore.jks
      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent1
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/zoo/secrets/zoo1.truststore.jks
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent1

      ZOOKEEPER_SSL_QUORUM: "true"
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_LOCATION: /etc/zoo/secrets/zoo1.keystore.jks
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_PASSWORD: confluent1
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_LOCATION: /etc/zoo/secrets/zoo1.truststore.jks
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_PASSWORD: confluent1
      ZOOKEEPER_SSL_QUORUM_HOSTNAME_VERIFICATION: "false"

    volumes:
      - ./certs/zoo:/etc/zoo/secrets
      - ./certs/jre-custom-certs:/usr/lib/jvm/jre/lib/security

  zoo2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zoo2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_SECURE_CLIENT_PORT: 3182
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2

      ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
      ZOOKEEPER_SERVER_CNXN_FACTORY: "org.apache.zookeeper.server.NettyServerCnxnFactory"
      ZOOKEEPER_AUTH_PROVIDER_X509: "org.apache.zookeeper.server.auth.X509AuthenticationProvider"
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/zoo/secrets/zoo2.keystore.jks
      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent2
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/zoo/secrets/zoo2.truststore.jks
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent2

      ZOOKEEPER_SSL_QUORUM: "true"
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_LOCATION: /etc/zoo/secrets/zoo2.keystore.jks
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_PASSWORD: confluent2
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_LOCATION: /etc/zoo/secrets/zoo2.truststore.jks
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_PASSWORD: confluent2
      ZOOKEEPER_SSL_QUORUM_HOSTNAME_VERIFICATION: "false"

    volumes:
      - ./certs/zoo:/etc/zoo/secrets
      - ./certs/jre-custom-certs:/usr/lib/jvm/jre/lib/security

  zoo3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zoo3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SECURE_CLIENT_PORT: 3183
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2

      ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888
      ZOOKEEPER_SERVER_CNXN_FACTORY: "org.apache.zookeeper.server.NettyServerCnxnFactory"
      ZOOKEEPER_AUTH_PROVIDER_X509: "org.apache.zookeeper.server.auth.X509AuthenticationProvider"
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/zoo/secrets/zoo3.keystore.jks
      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent3
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/zoo/secrets/zoo3.truststore.jks
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent3

      ZOOKEEPER_SSL_QUORUM: "true"
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_LOCATION: /etc/zoo/secrets/zoo3.keystore.jks
      ZOOKEEPER_SSL_QUORUM_KEYSTORE_PASSWORD: confluent3
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_LOCATION: /etc/zoo/secrets/zoo3.truststore.jks
      ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_PASSWORD: confluent3
      ZOOKEEPER_SSL_QUORUM_HOSTNAME_VERIFICATION: "false"

    volumes:
      - ./certs/zoo:/etc/zoo/secrets
      - ./certs/jre-custom-certs:/usr/lib/jvm/jre/lib/security

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL_SSL://kafka1:19092,LISTENER_DOCKER_EXTERNAL_SSL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL_SSL:SSL,LISTENER_DOCKER_EXTERNAL_SSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL_SSL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:3181,zoo2:3182,zoo3:3183"
      KAFKA_BROKER_ID: 1

      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: 1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: 1_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: 1_truststore_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: "org.apache.zookeeper.ClientCnxnSocketNetty"
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.broker1.keystore.jks
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent1
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.broker1.truststore.jks
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent1
      
    volumes:
      - ./certs/kafka:/etc/kafka/secrets
      - ./certs/jre-custom-certs:/usr/lib/jvm/jre/lib/security
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka2
    ports:
        - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL_SSL://kafka2:19093,LISTENER_DOCKER_EXTERNAL_SSL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL_SSL:SSL,LISTENER_DOCKER_EXTERNAL_SSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL_SSL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:3181,zoo2:3182,zoo3:3183"
      KAFKA_BROKER_ID: 2
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: 2_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: 2_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: 2_truststore_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: "org.apache.zookeeper.ClientCnxnSocketNetty"
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.broker2.keystore.jks
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent2
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.broker2.truststore.jks
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent2
    volumes:
      - ./certs/kafka:/etc/kafka/secrets
      - ./certs/jre-custom-certs:/usr/lib/jvm/jre/lib/security
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka3
    ports:
        - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL_SSL://kafka3:19094,LISTENER_DOCKER_EXTERNAL_SSL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL_SSL:SSL,LISTENER_DOCKER_EXTERNAL_SSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL_SSL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:3181,zoo2:3182,zoo3:3183"
      KAFKA_BROKER_ID: 3
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: 3_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: 3_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: 3_truststore_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: "true"
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: "org.apache.zookeeper.ClientCnxnSocketNetty"
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.broker3.keystore.jks
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent3
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.broker3.truststore.jks
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent3
    volumes:
      - ./certs/kafka:/etc/kafka/secrets
      - ./certs/jre-custom-certs:/usr/lib/jvm/jre/lib/security
    depends_on:
      - zoo1
      - zoo2
      - zoo3