ARG CODE_VERSION=latest
#ARG INFLUXDB_CONFIGFILE_NAME=config.yaml

FROM influxdb:${CODE_VERSION}

#COPY configs/influxdb/${INFLUXDB_CONFIGFILE_NAME} /
COPY certs/influxdb.crt /etc/ssl/certs/influxdb.crt
COPY certs/influxdb.key /etc/ssl/private/influxdb.key

#RUN /bin/bash -c 'chmod 644 /etc/ssl/certs/influxdb.crt; chmod 600 /etc/ssl/private/influxdb.key'
#RUN /bin/bash -c 'chown influxdb:influxdb /etc/ssl/certs/influxdb.crt; chown influxdb:influxdb /etc/ssl/private/influxdb.key'
